namespace DeepDungeonTracker;

public enum Coffer
{
    PomanderOfSafety,
    PomanderOfSight,
    PomanderOfStrength,
    PomanderOfSteel,
    PomanderOfAffluence,
    PomanderOfFlight,
    PomanderOfAlteration,
    PomanderOfPurity,
    PomanderOfFortune,
    PomanderOfWitching,
    PomanderOfSerenity,
    PomanderOfRage,
    PomanderOfLust,
    PomanderOfIntuition,
    PomanderOfRaising,
    PomanderOfResolution,
    PomanderOfFrailty,
    PomanderOfConcealment,
    PomanderOfPetrification,
    ProtomanderOfLethargy,
    ProtomanderOfStorms,
    ProtomanderOfDread,
    PomanderOfHaste,
    PomanderOfPurification,
    PomanderOfDevotion,
    Potsherd = 50,
    Medicine,
    Aetherpool,
    InfernoMagicite = 60,
    CragMagicite,
    VortexMagicite,
    ElderMagicite,
    UneiDemiclone,
    DogaDemiclone,
    OnionKnightDemiclone,
    JuniperIncense
}
